
spring:
  datasource:
    driver-class-name: ${dev-mysql-driver-class-name}
    url: ${dev-mysql-url}
    username: ${dev-mysql-username}
    password: ${dev-mysql-password}

dhf:
  jwt:
    secret: ${dev-jwt-secret}
    expiration: ${dev-jwt-expiration}
